---
- hosts: crossdorpoelem.be
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  post_tasks:
    - name: Start firewall
      service:
        name: ufw
        state: started
    - name: Enable firewall
      ufw:
        state: enabled

  roles:
    - { role: 'roles/website' }