version: "2.1"
services:

  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - cdo-site:site
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  cdo-site:
    image: cdo-site
