name: CI

on:
  push:
    branches:
      - master
      - 'cdo-*'
    tags-ignore:
      - '*.*'

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B verify

  package-and-publish:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - name: Set docker image tag
        run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF##*/}
      - name: Build docker image
        run: |
          cp site-main/target/cdo-site-*.jar deploy/docker/cdo-site.jar
          docker build -t wouterdhaeze/cdo-site:${IMAGE_TAG} deploy/docker
      - name: Push docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wouterdhaeze/cdo-site:${IMAGE_TAG}

  deploy-review:
    runs-on: ubuntu-latest
    needs: package-and-publish
    steps:
      - uses: actions/checkout@v2
      - name: Configure kubeconfig
        run: |
          echo "$KUBECONFIG_FILE" > /tmp/config
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG_DATA }}'
      - name: Set docker image tag
        run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF##*/}
      - name: Create pull secret
        run: |
          export KUBECONFIG=/tmp/config
          kubectl create secret docker-registry pull-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USER }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=wouter.dhaeze@gmail.com \
            -n default || true
      - name: Deploy review instance
        uses: 'deliverybot/helm@v1'
        with:
          release: 'cdo-site-review'
          namespace: 'default'
          chart: 'deploy/helm'
          helm: helm3
          values: |
            tag: ${IMAGE_TAG}
            commit: ${GITHUB_SHA}
          value-files: './deploy/review/values.yaml'
          timeout: 60s
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG_DATA }}'