name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  remove-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set docker image tag
        run: |
          echo ::set-env name=IMAGE_TAG::${{ github.head_ref }}
          echo "IMAGE_TAG: $IMAGE_TAG"
      - name: Delete docker tag
        run: |
          echo "Removing image tag '${{ github.head_ref }}'"
          chmod +x .github/scripts/delete-tag.sh
          .github/scripts/delete-tag.sh ${{ github.head_ref }}
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}