name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  remove-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set docker image tag
        run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF##*/}
      - name: Delete docker tag
        run: |
          chmod +x .github/scripts/delete-tag.sh
          .github/scripts/delete-tag.sh $IMAGE_TAG
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}